---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_facts:
    cloud: ospcloud
    region_name: RegionOne
  register: result

# tasks file for osp.servers
- name: Remove a server instance
  os_server:
    cloud: ospcloud
    name: "{{ item.name }}"
    state: absent
  register: ospserverstdout
  with_items: "{{result.ansible_facts.openstack_servers}}"
  