#!/bin/bash

TOWER_GUID=6fdf
OSP_GUID=5075
OPENTLC_LOGIN=dpalmer-au1.ibm.com
OPENTLC_PASSWORD=DAepZV8p6DLf
GITHUB_REPO=https://github.com/palmejim/ansible_advance_homework
JQ_REPO_BASE=http://www.opentlc.com/download/ansible_bootcamp
REGION=us-east-1
RH_MAIL_ID=dpalmer@au1.ibm.com

ansible-playbook site-config-tower.yml -e tower_GUID=${TOWER_GUID} -e osp_GUID=${OSP_GUID} -e opentlc_login=${OPENTLC_LOGIN} -e path_to_opentlc_key=/root/.ssh/mykey.pem -e param_repo_base=${JQ_REPO_BASE} -e opentlc_password=${OPENTLC_PASSWORD} -e REGION_NAME=${REGION} -e EMAIL=${RH_MAIL_ID} -e github_repo=${GITHUB_REPO}
